apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubewarden-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubewarden-controller.labels" . | nindent 4 }}
